# Generated by Django 6.0.6 on 2026-07-05 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('login', 'Вход'), ('logout', 'Выход'), ('loan', 'Выдача'), ('return', 'Возврат'), ('forced_return', 'Принудительный возврат'), ('user_created', 'Создание пользователя'), ('password_reset', 'Сброс пароля'), ('transfer', 'Перевод')], max_length=50, verbose_name='Действие')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='schools.school')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог действия',
                'verbose_name_plural': 'Логи действий',
                'ordering': ('-created_at',),
            },
        ),
    ]
