# Generated by Django 6.0.6 on 2026-07-10 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_transferlog_from_grade_alter_transferlog_to_school'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(choices=[('login', 'Вход'), ('logout', 'Выход'), ('loan', 'Выдача'), ('return', 'Возврат'), ('forced_return', 'Принудительный возврат'), ('user_created', 'Создание пользователя'), ('password_reset', 'Сброс пароля'), ('transfer', 'Перевод')], db_index=True, max_length=50, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='schools.school'),
        ),
    ]
