# Generated by Django 6.0.6 on 2026-07-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transfer_status',
            field=models.CharField(blank=True, choices=[('', 'Не в переводе'), ('departing', 'Ожидает ухода'), ('pending', 'Ожидает перевода'), ('completed', 'Переведён')], default='', max_length=20, verbose_name='Статус перевода'),
        ),
    ]
