# Generated by Django 6.0.6 on 2026-07-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_transfer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Логин'),
        ),
    ]
