# Generated by Django 6.0.6 on 2026-07-10 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_make_login_nullable'),
        ('schools', '0004_transferlog_from_grade_alter_transferlog_to_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_users', to='schools.class', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Суперадмин'), ('school_admin', 'Школьный админ'), ('teacher', 'Учитель'), ('student', 'Ученик')], db_index=True, default='student', max_length=20, verbose_name='Роль'),
        ),
    ]
