# Generated by Django 6.0.6 on 2026-07-05 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon_emoji', models.CharField(blank=True, max_length=10, verbose_name='Emoji')),
                ('category', models.CharField(choices=[('streak', 'Стрик'), ('books', 'Книги'), ('xp', 'XP'), ('challenge', 'Челлендж')], max_length=20, verbose_name='Категория')),
                ('condition', models.JSONField(default=dict, verbose_name='Условие получения')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(unique=True, verbose_name='Номер уровня')),
                ('xp_required', models.IntegerField(verbose_name='XP для достижения')),
                ('bonus_percent', models.IntegerField(default=0, verbose_name='Бонус XP в %')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_number', models.IntegerField(verbose_name='Класс')),
                ('language', models.CharField(max_length=10, verbose_name='Язык')),
                ('week_start', models.DateField(verbose_name='Начало недели')),
                ('questions', models.JSONField(default=list, verbose_name='Вопросы')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('closed', 'Закрыт')], default='draft', max_length=20, verbose_name='Статус')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='schools.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Челлендж',
                'verbose_name_plural': 'Челленджи',
                'ordering': ('-week_start',),
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_streak', models.IntegerField(default=0, verbose_name='Текущий стрик')),
                ('longest_streak', models.IntegerField(default=0, verbose_name='Максимальный стрик')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='Последняя активность')),
                ('frozen_days', models.IntegerField(default=0, verbose_name='Заморозки стрика')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='schools.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Стрик',
                'verbose_name_plural': 'Стрики',
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_xp', models.IntegerField(default=0, verbose_name='Всего XP')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.level', verbose_name='Уровень')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='level_info', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уровень пользователя',
                'verbose_name_plural': 'Уровни пользователей',
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(verbose_name='Количество XP')),
                ('reason', models.CharField(choices=[('return_ontime', 'Возврат вовремя'), ('return_late', 'Возврат с опозданием'), ('comeback_bonus', 'Камбэк-бонус'), ('challenge', 'Челлендж'), ('streak', 'Стрик'), ('achievement', 'Достижение')], max_length=50, verbose_name='Причина')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'XP транзакция',
                'verbose_name_plural': 'XP транзакции',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChallengeAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('answers', models.JSONField(default=dict, verbose_name='Ответы')),
                ('score', models.IntegerField(default=0, verbose_name='Баллы')),
                ('question_order', models.JSONField(default=list, verbose_name='Порядок вопросов')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершён')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='gamification.challenge', verbose_name='Челлендж')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Попытка челленджа',
                'verbose_name_plural': 'Попытки челленджей',
                'constraints': [models.UniqueConstraint(fields=('challenge', 'user'), name='unique_challenge_attempt')],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.achievement', verbose_name='Достижение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Достижение пользователя',
                'verbose_name_plural': 'Достижения пользователей',
                'constraints': [models.UniqueConstraint(fields=('user', 'achievement'), name='unique_user_achievement')],
            },
        ),
    ]
