# Generated by Django 6.0.6 on 2026-07-05 12:34

from django.db import migrations

ACHIEVEMENTS = [
    {'code': 'xp_100', 'name': 'Первые 100 XP', 'description': 'Накопи 100 XP', 'icon_emoji': '⭐', 'category': 'xp', 'condition': {'field': 'total_xp', 'gte': 100}},
    {'code': 'xp_1000', 'name': 'Охотник за XP', 'description': 'Накопи 1000 XP', 'icon_emoji': '🌟', 'category': 'xp', 'condition': {'field': 'total_xp', 'gte': 1000}},
    {'code': 'xp_10000', 'name': 'Легенда библиотеки', 'description': 'Накопи 10000 XP', 'icon_emoji': '💎', 'category': 'xp', 'condition': {'field': 'total_xp', 'gte': 10000}},
    {'code': 'streak_7', 'name': 'Недельный стрик', 'description': 'Посещай 7 дней подряд', 'icon_emoji': '🔥', 'category': 'streak', 'condition': {'field': 'streak', 'gte': 7}},
    {'code': 'streak_30', 'name': 'Месячный стрик', 'description': 'Посещай 30 дней подряд', 'icon_emoji': '💪', 'category': 'streak', 'condition': {'field': 'streak', 'gte': 30}},
    {'code': 'streak_100', 'name': 'Несгибаемый', 'description': 'Посещай 100 дней подряд', 'icon_emoji': '🏆', 'category': 'streak', 'condition': {'field': 'streak', 'gte': 100}},
    {'code': 'first_book', 'name': 'Первая книга', 'description': 'Верни первую книгу', 'icon_emoji': '📖', 'category': 'books', 'condition': {'field': 'books_returned', 'gte': 1}},
    {'code': 'bookworm_10', 'name': 'Читатель', 'description': 'Верни 10 книг', 'icon_emoji': '📚', 'category': 'books', 'condition': {'field': 'books_returned', 'gte': 10}},
    {'code': 'bookworm_50', 'name': 'Книжный червь', 'description': 'Верни 50 книг', 'icon_emoji': '🐛', 'category': 'books', 'condition': {'field': 'books_returned', 'gte': 50}},
    {'code': 'challenge_first', 'name': 'Первый челлендж', 'description': 'Пройди первый недельный челлендж', 'icon_emoji': '🧠', 'category': 'challenge', 'condition': {'field': 'challenges_done', 'gte': 1}},
    {'code': 'challenge_10', 'name': 'Чемпион челленджей', 'description': 'Пройди 10 челленджей', 'icon_emoji': '🎓', 'category': 'challenge', 'condition': {'field': 'challenges_done', 'gte': 10}},
]


def seed_achievements(apps, schema_editor):
    Achievement = apps.get_model('gamification', 'Achievement')
    for ach in ACHIEVEMENTS:
        Achievement.objects.get_or_create(code=ach['code'], defaults=ach)


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_achievements),
    ]
