# Generated by Django 6.0.6 on 2026-07-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_seed_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeattempt',
            name='time_limit_minutes',
            field=models.IntegerField(default=15, verbose_name='Лимит времени (мин)'),
        ),
    ]
