# Generated by Django 6.0.6 on 2026-07-05 12:44

from django.db import migrations

LEVELS = [
    {'number': 1, 'xp_required': 0, 'bonus_percent': 0},
    {'number': 2, 'xp_required': 100, 'bonus_percent': 2},
    {'number': 3, 'xp_required': 250, 'bonus_percent': 4},
    {'number': 4, 'xp_required': 500, 'bonus_percent': 6},
    {'number': 5, 'xp_required': 1000, 'bonus_percent': 8},
    {'number': 6, 'xp_required': 2000, 'bonus_percent': 10},
    {'number': 7, 'xp_required': 4000, 'bonus_percent': 12},
    {'number': 8, 'xp_required': 8000, 'bonus_percent': 14},
    {'number': 9, 'xp_required': 15000, 'bonus_percent': 16},
    {'number': 10, 'xp_required': 30000, 'bonus_percent': 20},
]


def seed_levels(apps, schema_editor):
    Level = apps.get_model('gamification', 'Level')
    for lvl in LEVELS:
        Level.objects.get_or_create(number=lvl['number'], defaults=lvl)


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_challengeattempt_time_limit_minutes'),
    ]

    operations = [
        migrations.RunPython(seed_levels),
    ]
