# Generated by Django 6.0.6 on 2026-07-10 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_seed_levels'),
        ('schools', '0004_transferlog_from_grade_alter_transferlog_to_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='condition',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('uz', 'Узбекский'), ('kaa', 'Каракалпакский'), ('en', 'Английский')], max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='streak',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='xptransaction',
            name='reason',
            field=models.CharField(choices=[('return_ontime', 'Возврат вовремя'), ('return_late', 'Возврат с опозданием'), ('comeback_bonus', 'Камбэк-бонус'), ('challenge', 'Челлендж'), ('streak', 'Стрик'), ('achievement', 'Достижение')], db_index=True, max_length=50, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='xptransaction',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='schools.school'),
        ),
        migrations.AddConstraint(
            model_name='challenge',
            constraint=models.UniqueConstraint(fields=('school', 'grade_number', 'language', 'week_start'), name='unique_challenge_per_week'),
        ),
    ]
