# Generated by Django 6.0.6 on 2026-07-05 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularBookLoan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата')),
                ('status', models.CharField(choices=[('active', 'Выдана'), ('returned', 'Возвращена'), ('forced', 'Принудительный возврат')], default='active', max_length=20, verbose_name='Статус')),
                ('qr_token', models.CharField(blank=True, max_length=500, verbose_name='QR-токен')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='catalog.regularbook', verbose_name='Книга')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_books', to=settings.AUTH_USER_MODEL, verbose_name='Выдал')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_loans', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Выдача книги',
                'verbose_name_plural': 'Выдачи книг',
                'ordering': ('-issued_at',),
            },
        ),
        migrations.CreateModel(
            name='TextbookLoan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('due_date', models.DateField(verbose_name='Срок возврата')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата')),
                ('status', models.CharField(choices=[('active', 'Выдан'), ('returned', 'Возвращён'), ('overdue', 'Просрочен'), ('forced', 'Принудительный возврат')], default='active', max_length=20, verbose_name='Статус')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_textbooks', to=settings.AUTH_USER_MODEL, verbose_name='Выдал')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbook_loans', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='catalog.textbook', verbose_name='Учебник')),
            ],
            options={
                'verbose_name': 'Выдача учебника',
                'verbose_name_plural': 'Выдачи учебников',
                'ordering': ('-issued_at',),
            },
        ),
    ]
