# Generated by Django 6.0.6 on 2026-07-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbookloan',
            name='borrower_type',
            field=models.CharField(choices=[('student', 'Ученик'), ('teacher', 'Учитель')], default='student', max_length=10, verbose_name='Тип заёмщика'),
        ),
    ]
