# Generated by Django 6.0.6 on 2026-07-05 13:32

import apps.loans.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_textbookloan_borrower_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularbookloan',
            name='due_date',
            field=models.DateField(default=apps.loans.models._default_due_date, verbose_name='Срок возврата'),
        ),
    ]
