# Generated by Django 6.0.6 on 2026-07-10 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_regularbookloan_due_date'),
        ('schools', '0004_transferlog_from_grade_alter_transferlog_to_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularbookloan',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='regularbookloan',
            name='status',
            field=models.CharField(choices=[('active', 'Выдана'), ('returned', 'Возвращена'), ('forced', 'Принудительный возврат')], db_index=True, default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='textbookloan',
            name='due_date',
            field=models.DateField(db_index=True, verbose_name='Срок возврата'),
        ),
        migrations.AlterField(
            model_name='textbookloan',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='textbookloan',
            name='status',
            field=models.CharField(choices=[('active', 'Выдан'), ('returned', 'Возвращён'), ('overdue', 'Просрочен'), ('forced', 'Принудительный возврат')], db_index=True, default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
