# Generated by Django 6.0.6 on 2026-07-05 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название района')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, verbose_name='Название школы')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='schools.district', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(verbose_name='Номер класса (1-11)')),
                ('parallel', models.CharField(max_length=50, verbose_name='Параллель')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('uz', 'Узбекский'), ('kaa', 'Каракалпакский'), ('en', 'Английский')], max_length=10, verbose_name='Язык обучения')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Учебный год')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('graduated', 'Выпускник')], default='active', max_length=20, verbose_name='Статус')),
                ('homeroom_teachers', models.ManyToManyField(blank=True, related_name='homeroom_classes', to=settings.AUTH_USER_MODEL, verbose_name='Классные руководители')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ('school', 'number', 'parallel'),
            },
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(fields=('name', 'district'), name='unique_school_per_district'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('number', 'parallel', 'language', 'academic_year', 'school'), name='unique_class_per_school_year'),
        ),
    ]
