# Generated by Django 6.0.6 on 2026-07-05 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('departing', 'Ожидает ухода'), ('pending', 'Ожидает перевода'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('xp_before', models.IntegerField(default=0, verbose_name='XP до перевода')),
                ('xp_after', models.IntegerField(default=0, verbose_name='XP после перевода')),
                ('from_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='schools.school', verbose_name='Из школы')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Инициировал')),
                ('to_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='schools.school', verbose_name='В школу')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог перевода',
                'verbose_name_plural': 'Логи переводов',
                'ordering': ('-created_at',),
            },
        ),
    ]
