# Generated by Django 6.0.6 on 2026-07-06 16:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_transferlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='Номер класса (1-11)'),
        ),
        migrations.CreateModel(
            name='PromotionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(max_length=20, verbose_name='Учебный год')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Инициировал')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='schools.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Лог автоперевода',
                'verbose_name_plural': 'Логи автопереводов',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('school', 'academic_year'), name='unique_promotion_per_school_year')],
            },
        ),
    ]
