# Generated by Django 6.0.7 on 2026-07-09 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_class_number_promotionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferlog',
            name='from_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='schools.class', verbose_name='Из класса'),
        ),
        migrations.AlterField(
            model_name='transferlog',
            name='to_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='schools.school', verbose_name='В школу'),
        ),
    ]
