# Generated by Django 6.0.6 on 2026-07-05 12:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RegularBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('author', models.CharField(blank=True, max_length=300, verbose_name='Автор')),
                ('cover', models.ImageField(blank=True, upload_to='covers/regular/', verbose_name='Обложка')),
                ('total_copies', models.PositiveIntegerField(default=1, verbose_name='Всего экземпляров')),
                ('available_copies', models.PositiveIntegerField(default=1, verbose_name='Доступно')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='catalog.category', verbose_name='Категория')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='schools.school')),
            ],
            options={
                'verbose_name': 'Обычная книга',
                'verbose_name_plural': 'Обычные книги',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('subject', models.CharField(max_length=200, verbose_name='Предмет')),
                ('grade_number', models.IntegerField(verbose_name='Класс')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('uz', 'Узбекский'), ('kaa', 'Каракалпакский'), ('en', 'Английский')], max_length=10, verbose_name='Язык')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Учебный год')),
                ('cover', models.ImageField(blank=True, upload_to='covers/textbooks/', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Учебник (справочник)',
                'verbose_name_plural': 'Учебники (справочник)',
                'ordering': ('subject', 'grade_number'),
                'constraints': [models.UniqueConstraint(fields=('title', 'subject', 'grade_number', 'language', 'academic_year'), name='unique_textbook')],
            },
        ),
        migrations.CreateModel(
            name='TextbookStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_copies', models.PositiveIntegerField(default=0, verbose_name='Всего экземпляров')),
                ('available_copies', models.PositiveIntegerField(default=0, verbose_name='Доступно')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='schools.school')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalog.textbook', verbose_name='Учебник')),
            ],
            options={
                'verbose_name': 'Остаток учебников',
                'verbose_name_plural': 'Остатки учебников',
                'constraints': [models.UniqueConstraint(fields=('school', 'textbook'), name='unique_stock_per_school')],
            },
        ),
    ]
