# Generated by Django 6.0.6 on 2026-07-05 12:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('schools', '0002_transferlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTextbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=200, verbose_name='Предмет')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_textbooks', to='schools.class', verbose_name='Класс')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='catalog.textbook', verbose_name='Учебник')),
            ],
            options={
                'verbose_name': 'Учебник по предмету класса',
                'verbose_name_plural': 'Учебники по предметам классов',
                'constraints': [models.UniqueConstraint(fields=('school_class', 'subject'), name='unique_subject_per_class')],
            },
        ),
    ]
