# Generated by Django 6.0.6 on 2026-07-10 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_subjecttextbook'),
        ('schools', '0004_transferlog_from_grade_alter_transferlog_to_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularbook',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='textbookstock',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='schools.school'),
        ),
    ]
